export interface Country {
  code: string;
  name: string;
  flag: string;
  flagUrl: string;
  ibanPrefix?: string;
  leagues?: string[];
}

export const ALL_COUNTRIES: Country[] = [
  {"code":"PT","name":"Portugal","flag":"🇵🇹","flagUrl":"https://flagcdn.com/pt.svg","ibanPrefix":"PT50","leagues":["Liga Portugal","Liga Portugal 2","Taça de Portugal", "Taça da Liga"]},
  {"code":"DE","name":"Alemanha","flag":"🇩🇪","flagUrl":"https://flagcdn.com/de.svg","ibanPrefix":"DE","leagues":["Bundesliga","2. Bundesliga","DFB Pokal"]},
  {"code":"BE","name":"Bélgica","flag":"🇧🇪","flagUrl":"https://flagcdn.com/be.svg","ibanPrefix":"BE","leagues":["Jupiler Pro League","Belgian Cup"]},
  {"code":"DK","name":"Dinamarca","flag":"🇩🇰","flagUrl":"https://flagcdn.com/dk.svg","ibanPrefix":"DK","leagues":["Superliga","Danish Cup"]},
  {"code":"ES","name":"Espanha","flag":"🇪🇸","flagUrl":"https://flagcdn.com/es.svg","ibanPrefix":"ES","leagues":["La Liga","La Liga 2","Copa del Rey"]},
  {"code":"FR","name":"França","flag":"🇫🇷","flagUrl":"https://flagcdn.com/fr.svg","ibanPrefix":"FR","leagues":["Ligue 1","Ligue 2","Coupe de France"]},
  {"code":"GR","name":"Grécia","flag":"🇬🇷","flagUrl":"https://flagcdn.com/gr.svg","ibanPrefix":"GR","leagues":["Super League 1","Greek Cup"]},
  {"code":"IT","name":"Itália","flag":"🇮🇹","flagUrl":"https://flagcdn.com/it.svg","ibanPrefix":"IT","leagues":["Serie A","Serie B","Coppa Italia"]},
  {"code":"NL","name":"Países Baixos","flag":"🇳🇱","flagUrl":"https://flagcdn.com/nl.svg","ibanPrefix":"NL","leagues":["Eredivisie","Eerste Divisie","KNVB Beker"]},
  {"code":"GB-ENG","name":"Inglaterra","flag":"🇬🇧","flagUrl":"https://flagcdn.com/gb-eng.svg","leagues":["Premier League","Championship","FA Cup","EFL Cup", "League One", "League Two"]},
  {"code":"GB-SCT","name":"Escócia","flag":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","flagUrl":"https://flagcdn.com/gb-sct.svg","leagues":["Premiership","Scottish Cup", "Championship"]},
  {"code":"GB-WLS","name":"País de Gales","flag":"🏴󠁧󠁢󠁷󠁬󠁳󠁿","flagUrl":"https://flagcdn.com/gb-wls.svg","leagues":["Cymru Premier"]},
  {"code":"GB-NIR","name":"Irlanda do Norte","flag":"🏴","flagUrl":"https://flagcdn.com/gb-nir.svg","leagues":["NIFL Premiership"]},
  {"code":"IE","name":"Irlanda","flag":"🇮🇪","flagUrl":"https://flagcdn.com/ie.svg","leagues":["Premier Division"]},
  {"code":"TR","name":"Turquia","flag":"🇹🇷","flagUrl":"https://flagcdn.com/tr.svg","leagues":["Süper Lig","Turkish Cup", "1. Lig"]},
  {"code":"CH","name":"Suíça","flag":"🇨🇭","flagUrl":"https://flagcdn.com/ch.svg","leagues":["Super League", "Swiss Cup", "Challenge League"]},
  {"code":"AT","name":"Áustria","flag":"🇦🇹","flagUrl":"https://flagcdn.com/at.svg","leagues":["Bundesliga", "2. Liga"]},
  {"code":"PL","name":"Polônia","flag":"🇵🇱","flagUrl":"https://flagcdn.com/pl.svg","leagues":["Ekstraklasa", "I Liga"]},
  {"code":"CZ","name":"República Checa","flag":"🇨🇿","flagUrl":"https://flagcdn.com/cz.svg","leagues":["Fortuna Liga"]},
  {"code":"HU","name":"Hungria","flag":"🇭🇺","flagUrl":"https://flagcdn.com/hu.svg","leagues":["NB I"]},
  {"code":"RO","name":"Romênia","flag":"🇷🇴","flagUrl":"https://flagcdn.com/ro.svg","leagues":["Liga I"]},
  {"code":"BG","name":"Bulgária","flag":"🇧🇬","flagUrl":"https://flagcdn.com/bg.svg","leagues":["Parva Liga"]},
  {"code":"RS","name":"Sérvia","flag":"🇷🇸","flagUrl":"https://flagcdn.com/rs.svg","leagues":["SuperLiga"]},
  {"code":"HR","name":"Croácia","flag":"🇭🇷","flagUrl":"https://flagcdn.com/hr.svg","leagues":["HNL"]},
  {"code":"RU","name":"Rússia","flag":"🇷🇺","flagUrl":"https://flagcdn.com/ru.svg","leagues":["Premier League"]},
  {"code":"UA","name":"Ucrânia","flag":"🇺🇦","flagUrl":"https://flagcdn.com/ua.svg","leagues":["Premier League"]},
  {"code":"SE","name":"Suécia","flag":"🇸🇪","flagUrl":"https://flagcdn.com/se.svg","leagues":["Allsvenskan", "Superettan"]},
  {"code":"NO","name":"Noruega","flag":"🇳🇴","flagUrl":"https://flagcdn.com/no.svg","leagues":["Eliteserien", "OBOS-ligaen"]},
  {"code":"FI","name":"Finlândia","flag":"🇫🇮","flagUrl":"https://flagcdn.com/fi.svg","leagues":["Veikkausliiga"]},
  {"code":"IS","name":"Islândia","flag":"🇮🇸","flagUrl":"https://flagcdn.com/is.svg","leagues":["Besta deild karla"]},
  {"code":"BR","name":"Brasil","flag":"🇧🇷","flagUrl":"https://flagcdn.com/br.svg","leagues":["Brasileirão Série A","Brasileirão Série B","Brasileirão Série C","Brasileirão Série D","Copa do Brasil","Paulistão","Carioca"]},
  {"code":"AR","name":"Argentina","flag":"🇦🇷","flagUrl":"https://flagcdn.com/ar.svg","leagues":["Liga Profesional","Copa Argentina", "Primera Nacional"]},
  {"code":"UY","name":"Uruguai","flag":"🇺🇾","flagUrl":"https://flagcdn.com/uy.svg","leagues":["Primera División"]},
  {"code":"CL","name":"Chile","flag":"🇨🇱","flagUrl":"https://flagcdn.com/cl.svg","leagues":["Primera División"]},
  {"code":"CO","name":"Colômbia","flag":"🇨🇴","flagUrl":"https://flagcdn.com/co.svg","leagues":["Primera A","Primera B","Copa Colombia"]},
  {"code":"PE","name":"Peru","flag":"🇵🇪","flagUrl":"https://flagcdn.com/pe.svg","leagues":["Liga 1"]},
  {"code":"EC","name":"Equador","flag":"🇪🇨","flagUrl":"https://flagcdn.com/ec.svg","leagues":["Liga Pro"]},
  {"code":"PY","name":"Paraguai","flag":"🇵🇾","flagUrl":"https://flagcdn.com/py.svg","leagues":["Primera División"]},
  {"code":"BO","name":"Bolívia","flag":"🇧🇴","flagUrl":"https://flagcdn.com/bo.svg","leagues":["Primera División"]},
  {"code":"VE","name":"Venezuela","flag":"🇻🇪","flagUrl":"https://flagcdn.com/ve.svg","leagues":["Primera División"]},
  {"code":"US","name":"EUA","flag":"🇺🇸","flagUrl":"https://flagcdn.com/us.svg","leagues":["MLS","US Open Cup", "USL"]},
  {"code":"MX","name":"México","flag":"🇲🇽","flagUrl":"https://flagcdn.com/mx.svg","leagues":["Liga MX","Copa MX", "Liga de Expansión MX"]},
  {"code":"CA","name":"Canadá","flag":"🇨🇦","flagUrl":"https://flagcdn.com/ca.svg","leagues":["Canadian Premier League"]},
  {"code":"CR","name":"Costa Rica","flag":"🇨🇷","flagUrl":"https://flagcdn.com/cr.svg","leagues":["Primera División"]},
  {"code":"JP","name":"Japão","flag":"🇯🇵","flagUrl":"https://flagcdn.com/jp.svg","leagues":["J1 League","J2 League","Emperor's Cup"]},
  {"code":"KR","name":"Coreia do Sul","flag":"🇰🇷","flagUrl":"https://flagcdn.com/kr.svg","leagues":["K League 1", "K League 2"]},
  {"code":"CN","name":"China","flag":"🇨🇳","flagUrl":"https://flagcdn.com/cn.svg","leagues":["Super League"]},
  {"code":"SA","name":"Arábia Saudita","flag":"🇸🇦","flagUrl":"https://flagcdn.com/sa.svg","leagues":["Saudi Pro League"]},
  {"code":"QA","name":"Catar","flag":"🇶🇦","flagUrl":"https://flagcdn.com/qa.svg","leagues":["Stars League"]},
  {"code":"AE","name":"Emirados Árabes","flag":"🇦🇪","flagUrl":"https://flagcdn.com/ae.svg","leagues":["Pro League"]},
  {"code":"IR","name":"Irã","flag":"🇮🇷","flagUrl":"https://flagcdn.com/ir.svg","leagues":["Pro League"]},
  {"code":"AU","name":"Austrália","flag":"🇦🇺","flagUrl":"https://flagcdn.com/au.svg","leagues":["A-League"]},
  {"code":"NZ","name":"Nova Zelândia","flag":"🇳🇿","flagUrl":"https://flagcdn.com/nz.svg","leagues":["National League"]},
  {"code":"ZA","name":"África do Sul","flag":"🇿🇦","flagUrl":"https://flagcdn.com/za.svg","leagues":["Premier Soccer League"]},
  {"code":"EG","name":"Egito","flag":"🇪🇬","flagUrl":"https://flagcdn.com/eg.svg","leagues":["Premier League"]},
  {"code":"MA","name":"Marrocos","flag":"🇲🇦","flagUrl":"https://flagcdn.com/ma.svg","leagues":["Botola Pro"]},
  {"code":"TN","name":"Tunísia","flag":"🇹🇳","flagUrl":"https://flagcdn.com/tn.svg","leagues":["Ligue 1"]},
  {"code":"DZ","name":"Argélia","flag":"🇩🇿","flagUrl":"https://flagcdn.com/dz.svg","leagues":["Ligue 1"]},
  {"code":"GH","name":"Gana","flag":"🇬🇭","flagUrl":"https://flagcdn.com/gh.svg","leagues":["Premier League"]},
  {"code":"NG","name":"Nigéria","flag":"🇳🇬","flagUrl":"https://flagcdn.com/ng.svg","leagues":["NPFL"]},
  {"code":"CM","name":"Camarões","flag":"🇨🇲","flagUrl":"https://flagcdn.com/cm.svg","leagues":["Elite One"]},
  {"code":"SN","name":"Senegal","flag":"🇸🇳","flagUrl":"https://flagcdn.com/sn.svg","leagues":["Ligue 1"]},
  {"code":"CI","name":"Costa do Marfim","flag":"🇨🇮","flagUrl":"https://flagcdn.com/ci.svg","leagues":["Ligue 1"]},
  {"code":"JM","name":"Jamaica","flag":"🇯🇲","flagUrl":"https://flagcdn.com/jm.svg","leagues":["Jamaica Premier League"]},
  {"code":"TH","name":"Tailândia","flag":"🇹🇭","flagUrl":"https://flagcdn.com/th.svg","leagues":["Thai League 1"]},
  {"code":"VN","name":"Vietnã","flag":"🇻🇳","flagUrl":"https://flagcdn.com/vn.svg","leagues":["V.League 1"]},
  {"code":"ID","name":"Indonésia","flag":"🇮🇩","flagUrl":"https://flagcdn.com/id.svg","leagues":["Liga 1"]},
  {"code":"MY","name":"Malásia","flag":"🇲🇾","flagUrl":"https://flagcdn.com/my.svg","leagues":["Super League"]},
  {"code":"SG","name":"Singapura","flag":"🇸🇬","flagUrl":"https://flagcdn.com/sg.svg","leagues":["Premier League"]},
  {"code":"IN","name":"Índia","flag":"🇮🇳","flagUrl":"https://flagcdn.com/in.svg","leagues":["ISL", "I-League"]},
  {"code":"IL","name":"Israel","flag":"🇮🇱","flagUrl":"https://flagcdn.com/il.svg","leagues":["Premier League"]},
  {"code":"CY","name":"Chipre","flag":"🇨🇾","flagUrl":"https://flagcdn.com/cy.svg","leagues":["First Division"]},
  {"code":"AZ","name":"Azerbaijão","flag":"🇦🇿","flagUrl":"https://flagcdn.com/az.svg","leagues":["Premier League"]},
  {"code":"GE","name":"Geórgia","flag":"🇬🇪","flagUrl":"https://flagcdn.com/ge.svg","leagues":["Erovnuli Liga"]},
  {"code":"AM","name":"Armênia","flag":"🇦🇲","flagUrl":"https://flagcdn.com/am.svg","leagues":["Premier League"]},
  {"code":"KZ","name":"Cazaquistão","flag":"🇰🇿","flagUrl":"https://flagcdn.com/kz.svg","leagues":["Premier League"]},
  {"code":"UZ","name":"Uzbequistão","flag":"🇺🇿","flagUrl":"https://flagcdn.com/uz.svg","leagues":["Super League"]},
  {"code":"BY","name":"Bielorrússia","flag":"🇧🇾","flagUrl":"https://flagcdn.com/by.svg","leagues":["Premier League"]},
  {"code":"MD","name":"Moldávia","flag":"🇲🇩","flagUrl":"https://flagcdn.com/md.svg","leagues":["Super Liga"]},
  {"code":"LV","name":"Letônia","flag":"🇱🇻","flagUrl":"https://flagcdn.com/lv.svg","leagues":["Higher League"]},
  {"code":"LT","name":"Lituânia","flag":"🇱🇹","flagUrl":"https://flagcdn.com/lt.svg","leagues":["A Lyga"]},
  {"code":"EE","name":"Estônia","flag":"🇪🇪","flagUrl":"https://flagcdn.com/ee.svg","leagues":["Meistriliiga"]},
  {"code":"AL","name":"Albânia","flag":"🇦🇱","flagUrl":"https://flagcdn.com/al.svg","leagues":["Kategoria Superiore"]},
  {"code":"MK","name":"Macedônia do Norte","flag":"🇲🇰","flagUrl":"https://flagcdn.com/mk.svg","leagues":["First League"]},
  {"code":"BA","name":"Bósnia e Herzegovina","flag":"🇧🇦","flagUrl":"https://flagcdn.com/ba.svg","leagues":["Premier League"]},
  {"code":"ME","name":"Montenegro","flag":"🇲🇪","flagUrl":"https://flagcdn.com/me.svg","leagues":["First League"]},
  {"code":"XK","name":"Kosovo","flag":"🇽🇰","flagUrl":"https://flagcdn.com/xk.svg","leagues":["Superliga"]},
  {"code":"MT","name":"Malta","flag":"🇲🇹","flagUrl":"https://flagcdn.com/mt.svg","leagues":["Premier League"]},
  {"code":"AD","name":"Andorra","flag":"🇦🇩","flagUrl":"https://flagcdn.com/ad.svg","leagues":["Primera Divisió"]},
  {"code":"SM","name":"San Marino","flag":"🇸🇲","flagUrl":"https://flagcdn.com/sm.svg","leagues":["Campionato Sammarinese"]},
  {"code":"GI","name":"Gibraltar","flag":"🇬🇮","flagUrl":"https://flagcdn.com/gi.svg","leagues":["National League"]},
  {"code":"FO","name":"Ilhas Faroé","flag":"🇫🇴","flagUrl":"https://flagcdn.com/fo.svg","leagues":["Premier League"]},
  {"code":"LU","name":"Luxemburgo","flag":"🇱🇺","flagUrl":"https://flagcdn.com/lu.svg","leagues":["National Division"]},
  {"code":"LI","name":"Liechtenstein","flag":"🇱🇮","flagUrl":"https://flagcdn.com/li.svg","leagues":["Cup"]},
  {"code":"PA","name":"Panamá","flag":"🇵🇦","flagUrl":"https://flagcdn.com/pa.svg","leagues":["LPF"]},
  {"code":"SV","name":"El Salvador","flag":"🇸🇻","flagUrl":"https://flagcdn.com/sv.svg","leagues":["Primera División"]},
  {"code":"GT","name":"Guatemala","flag":"🇬🇹","flagUrl":"https://flagcdn.com/gt.svg","leagues":["Liga Nacional"]},
  {"code":"HN","name":"Honduras","flag":"🇭🇳","flagUrl":"https://flagcdn.com/hn.svg","leagues":["Liga Nacional"]},
  {"code":"NI","name":"Nicarágua","flag":"🇳🇮","flagUrl":"https://flagcdn.com/ni.svg","leagues":["Liga Primera"]},
  {"code":"EU","name":"Europa","flag":"🇪🇺","flagUrl":"https://flagcdn.com/eu.svg","leagues":["Champions League", "Europa League", "Conference League", "Euro Qualification"]},
  {"code":"WO","name":"Mundo","flag":"🌍","flagUrl":"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/1f30d.svg","leagues":["World Cup", "Friendly International", "Club Friendlies", "Olympics"]}
];

export const SUPPORTED_COUNTRIES = ALL_COUNTRIES.filter(c => c.ibanPrefix);

export const getCountry = (code: string) => ALL_COUNTRIES.find(c => c.code === code);
